services:
  vaistynas_nginx:
    container_name: vaistynas_nginx
    build: ./nginx
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - ../ssl:/etc/nginx/ssl
  vaistynas_node:
    container_name: vaistynas_node
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    user: "node"
    networks:
      - web
    volumes:
      - ../src/frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - vaistynas_nginx

networks:
  web:
    external: true