# pull the Node.js Docker image
FROM node:19-bullseye

# create the directory inside the container
WORKDIR /app

ENTRYPOINT ["tail", "-f", "/dev/null"]
#COPY ./src/frontend .

#RUN npm install

#CMD ["npm", "run", "dev"]

#ENTRYPOINT ["tail", "-f", "/dev/null"]

# our app is running on port 1000 within the container, so need to expose it
#EXPOSE 3000